(() => {
  const { clamp, lerp, damp, interpolateKeyframes, sequenceWeights, chapterData, smootherstep } = window.TaidianStoryMath;
  const story=document.getElementById('scrollStory');
  const scene=document.getElementById('scene');
  const canvas=document.getElementById('service-overlay');
  const context=canvas.getContext('2d',{alpha:true,desynchronized:true});
  const scanLine=document.getElementById('scanLine');
  const copyStates=[...document.querySelectorAll('[data-copy-state]')];
  const tabs=[...document.querySelectorAll('.state-tab')];
  const topButtons=[...document.querySelectorAll('.topnav [data-state]')];
  const code=document.getElementById('chapterCode');
  const progressFill=document.getElementById('progressFill');
  const modelLabel=document.getElementById('modelLabel');
  const nextButton=document.getElementById('nextState');
  const root=document.documentElement;
  const labels=['LAYER / DAILY SERVICE','LAYER / EXPERIENCE SIGNAL','LAYER / RENEWAL TRACE','LAYER / VALUE PATH','LAYER / PARTNERSHIP'];
  const focuses=[[0,1,2,4,6],[1,3,5,7,8],[0,2,3,6,9],[2,4,5,8,9],[0,1,4,7,9]];
  const focusSets=focuses.map(items=>new Set(items));
  const positions=[[[.13,.24],[.31,.18],[.52,.25],[.74,.18],[.88,.34],[.22,.48],[.43,.44],[.63,.47],[.81,.56],[.56,.72]],[[.18,.19],[.37,.22],[.55,.17],[.78,.25],[.9,.4],[.25,.44],[.46,.49],[.67,.42],[.8,.62],[.55,.76]],[[.12,.31],[.28,.16],[.49,.32],[.7,.2],[.87,.3],[.2,.55],[.4,.47],[.62,.55],[.84,.51],[.54,.75]],[[.1,.23],[.3,.23],[.5,.23],[.7,.23],[.9,.23],[.2,.51],[.4,.51],[.6,.51],[.8,.51],[.5,.76]],[[.15,.2],[.34,.17],[.52,.23],[.72,.17],[.87,.33],[.24,.49],[.44,.43],[.64,.49],[.82,.58],[.56,.7]]];
  const edges=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[6,9],[2,6],[4,8],[7,9]];
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const imageSequence=[0,0,1,2,3];
  const imageIntensity=[.82,.90,.92,.88,.95];
  const contentEnd=.84,handoffStart=.88;
  let width=1,height=1,ratio=1,storyStart=0,storyDistance=1,targetProgress=0,displayProgress=0;
  let pointerTargetX=0,pointerTargetY=0,pointerX=0,pointerY=0,animationFrame=0,measureFrame=0,lastFrameTime=0,activeState=-1;
  const createGlow=()=>{const sprite=document.createElement('canvas');sprite.width=48;sprite.height=48;const ctx=sprite.getContext('2d'),g=ctx.createRadialGradient(24,24,0,24,24,24);g.addColorStop(0,'rgba(246,194,111,.9)');g.addColorStop(.25,'rgba(246,194,111,.28)');g.addColorStop(1,'rgba(246,194,111,0)');ctx.fillStyle=g;ctx.fillRect(0,0,48,48);return sprite};
  const glow=createGlow();
  function applyImageState(progress){const imageWeights=sequenceWeights(progress,imageSequence,4),intensity=interpolateKeyframes(progress,imageIntensity);imageWeights.forEach((weight,index)=>{root.style.setProperty(`--image-${index}-opacity`,(weight*intensity).toFixed(4));root.style.setProperty(`--image-${index}-x`,`${((index-1.5)*5+progress*(index%2?-7:9)+pointerX*-4).toFixed(2)}px`);root.style.setProperty(`--image-${index}-scale`,(1.035+progress*.045+index*.004).toFixed(4))})}
  function updateCopy(state){const{from,to,mix}=state;copyStates.forEach(el=>{el.style.opacity='0';el.style.transform='translate3d(0,20px,0)'});const blend=from===to?0:smootherstep(clamp((mix-.3)/.4));copyStates[from].style.opacity=(1-blend).toFixed(3);copyStates[from].style.transform=`translate3d(0,${(-14*blend).toFixed(2)}px,0)`;if(to!==from){copyStates[to].style.opacity=blend.toFixed(3);copyStates[to].style.transform=`translate3d(0,${(18*(1-blend)).toFixed(2)}px,0)`}const next=blend<.5?from:to;if(next!==activeState){activeState=next;code.textContent=`${String(activeState+1).padStart(3,'0')} / 005`;modelLabel.textContent=labels[activeState];nextButton.innerHTML=activeState===4?'进入合作 <span>↓</span>':'继续滚动 <span>↓</span>';[...tabs,...topButtons].forEach(btn=>{const active=Number(btn.dataset.state)===activeState;btn.classList.toggle('is-active',active);btn.setAttribute('aria-current',active?'step':'false')});copyStates.forEach((el,i)=>el.setAttribute('aria-hidden',i===activeState?'false':'true'))}}
  function draw(progress){const state=chapterData(progress,5),focusA=focusSets[state.from],focusB=focusSets[state.to];context.clearRect(0,0,width,height);const points=positions[state.from].map((p,i)=>({x:lerp(p[0],positions[state.to][i][0],state.mix)*width+pointerX*8*(p[0]-.5),y:lerp(p[1],positions[state.to][i][1],state.mix)*height+pointerY*5*(p[1]-.5)}));edges.forEach(([a,b],index)=>{const pa=points[a],pb=points[b],weight=lerp(focusA.has(a)||focusA.has(b)?1:0,focusB.has(a)||focusB.has(b)?1:0,state.mix);context.strokeStyle=`rgba(230,238,233,${.12+weight*.28})`;context.lineWidth=.55+weight*.45;context.beginPath();context.moveTo(pa.x,pa.y);context.lineTo(pb.x,pb.y);context.stroke();if(weight>.35){const flow=(progress*4.1+index*.13)%1,x=lerp(pa.x,pb.x,flow),y=lerp(pa.y,pb.y,flow);context.globalAlpha=.35+weight*.55;context.drawImage(glow,x-14,y-14,28,28);context.globalAlpha=1}});points.forEach((p,i)=>{const weight=lerp(focusA.has(i)?1:0,focusB.has(i)?1:0,state.mix);if(weight>.2){context.globalAlpha=weight*.55;context.drawImage(glow,p.x-18,p.y-18,36,36);context.globalAlpha=1}context.fillStyle=weight>.35?'rgba(246,198,119,.96)':'rgba(225,235,229,.58)';context.beginPath();context.arc(p.x,p.y,1.4+weight*1.4,0,Math.PI*2);context.fill();context.strokeStyle=`rgba(236,242,238,${.16+weight*.38})`;context.lineWidth=.7;context.beginPath();context.arc(p.x,p.y,5+weight*4,0,Math.PI*2);context.stroke()});root.style.setProperty('--scan-x',`${(progress*width).toFixed(2)}px`);updateCopy(state);progressFill.style.transform=`scaleX(${progress.toFixed(5)})`}
  function renderFrame(now){const delta=lastFrameTime?Math.min(.05,Math.max(.001,(now-lastFrameTime)/1000)):1/60;lastFrameTime=now;if(reducedMotion){displayProgress=targetProgress;pointerX=pointerTargetX;pointerY=pointerTargetY}else{displayProgress=damp(displayProgress,targetProgress,17,delta);pointerX=damp(pointerX,pointerTargetX,12,delta);pointerY=damp(pointerY,pointerTargetY,12,delta)}const content=clamp(displayProgress/contentEnd),handoff=smootherstep(clamp((displayProgress-handoffStart)/(1-handoffStart)));applyImageState(content);draw(content);root.style.setProperty('--handoff',handoff.toFixed(5));root.style.setProperty('--shell-y',`${(-handoff*18).toFixed(2)}px`);const moving=Math.abs(displayProgress-targetProgress)>.00012||Math.abs(pointerX-pointerTargetX)>.0005||Math.abs(pointerY-pointerTargetY)>.0005;if(moving)animationFrame=requestAnimationFrame(renderFrame);else{displayProgress=targetProgress;animationFrame=0}}
  function scheduleRender(){if(animationFrame)return;lastFrameTime=performance.now();animationFrame=requestAnimationFrame(renderFrame)}function updateTargetFromScroll(){targetProgress=clamp((scrollY-storyStart)/storyDistance)}function onScroll(){updateTargetFromScroll();scheduleRender()}
  function resizeCanvas(){const rect=canvas.getBoundingClientRect(),limit=innerWidth<=720?1.2:1.4;ratio=Math.min(devicePixelRatio||1,limit);width=Math.max(1,rect.width);height=Math.max(1,rect.height);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);context.setTransform(ratio,0,0,ratio,0,0)}
  function measure(){measureFrame=0;const rect=story.getBoundingClientRect();storyStart=scrollY+rect.top;storyDistance=Math.max(1,story.offsetHeight-innerHeight);resizeCanvas();updateTargetFromScroll();if(!displayProgress)displayProgress=targetProgress;scheduleRender()}function scheduleMeasure(){if(measureFrame)return;measureFrame=requestAnimationFrame(measure)}
  function scrollToState(index){const normalized=clamp(index/4)*contentEnd;scrollTo({top:storyStart+storyDistance*normalized,behavior:reducedMotion?'auto':'smooth'})}
  tabs.forEach(btn=>btn.addEventListener('click',()=>scrollToState(Number(btn.dataset.state))));topButtons.forEach(btn=>btn.addEventListener('click',()=>scrollToState(Number(btn.dataset.state))));nextButton.addEventListener('click',()=>activeState<4?scrollToState(activeState+1):scrollTo({top:storyStart+storyDistance,behavior:reducedMotion?'auto':'smooth'}));scene.addEventListener('pointermove',e=>{const rect=scene.getBoundingClientRect();pointerTargetX=((e.clientX-rect.left)/rect.width-.5)*2;pointerTargetY=((e.clientY-rect.top)/rect.height-.5)*2;scheduleRender()});scene.addEventListener('pointerleave',()=>{pointerTargetX=0;pointerTargetY=0;scheduleRender()});addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',scheduleMeasure,{passive:true});new ResizeObserver(scheduleMeasure).observe(story);measure();
})();
