(() => {
  const story=document.getElementById('scrollStory'),scene=document.getElementById('scene'),canvas=document.getElementById('service-overlay'),ctx=canvas.getContext('2d'),scanLine=document.getElementById('scanLine');
  const copyStates=[...document.querySelectorAll('[data-copy-state]')],tabs=[...document.querySelectorAll('.state-tab')],topButtons=[...document.querySelectorAll('.topnav [data-state]')];
  const code=document.getElementById('chapterCode'),progressFill=document.getElementById('progressFill'),modelLabel=document.getElementById('modelLabel'),nextButton=document.getElementById('nextState');
  const labels=['LAYER / DAILY SERVICE','LAYER / EXPERIENCE SIGNAL','LAYER / RENEWAL TRACE','LAYER / VALUE PATH','LAYER / PARTNERSHIP'];
  const focuses=[[0,1,2,4,6],[1,3,5,7,8],[0,2,3,6,9],[2,4,5,8,9],[0,1,4,7,9]];
  const positions=[
    [[.13,.24],[.31,.18],[.52,.25],[.74,.18],[.88,.34],[.22,.48],[.43,.44],[.63,.47],[.81,.56],[.56,.72]],
    [[.18,.19],[.37,.22],[.55,.17],[.78,.25],[.9,.4],[.25,.44],[.46,.49],[.67,.42],[.8,.62],[.55,.76]],
    [[.12,.31],[.28,.16],[.49,.32],[.7,.2],[.87,.3],[.2,.55],[.4,.47],[.62,.55],[.84,.51],[.54,.75]],
    [[.1,.23],[.3,.23],[.5,.23],[.7,.23],[.9,.23],[.2,.51],[.4,.51],[.6,.51],[.8,.51],[.5,.76]],
    [[.15,.2],[.34,.17],[.52,.23],[.72,.17],[.87,.33],[.24,.49],[.44,.43],[.64,.49],[.82,.58],[.56,.7]]
  ];
  const edges=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[6,9],[2,6],[4,8],[7,9]];
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  let width=1,height=1,ratio=1,pointerX=0,pointerY=0,storyProgress=0,segmentProgress=0,activeState=0,raf=0;
  const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t);
  function resize(){const rect=canvas.getBoundingClientRect();ratio=Math.min(devicePixelRatio||1,2);width=Math.max(1,rect.width);height=Math.max(1,rect.height);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);scheduleRender()}
  function currentScrollProgress(){return clamp((scrollY-story.offsetTop)/Math.max(1,story.offsetHeight-innerHeight))}
  function stateData(progress){const scaled=progress*4,from=Math.floor(scaled),to=Math.min(4,from+1),mix=ease(scaled-from);return{scaled,from,to,mix}}
  function updateCopy(scaled){copyStates.forEach((el,i)=>{const d=Math.abs(scaled-i),opacity=clamp(1-d*1.45);el.style.opacity=opacity.toFixed(3);el.style.transform=`translateY(${(i-scaled)*22}px)`;el.setAttribute('aria-hidden',opacity<.45?'true':'false')});activeState=Math.round(scaled);code.textContent=`${String(activeState+1).padStart(3,'0')} / 005`;modelLabel.textContent=labels[activeState];[...tabs,...topButtons].forEach(btn=>{const active=Number(btn.dataset.state)===activeState;btn.classList.toggle('is-active',active);btn.setAttribute('aria-current',active?'step':'false')})}
  function draw(){const{scaled,from,to,mix}=stateData(storyProgress);segmentProgress=mix;ctx.clearRect(0,0,width,height);const points=positions[from].map((p,i)=>({x:(lerp(p[0],positions[to][i][0],mix)*width)+pointerX*8*(p[0]-.5),y:(lerp(p[1],positions[to][i][1],mix)*height)+pointerY*5*(p[1]-.5)}));const focusA=new Set(focuses[from]),focusB=new Set(focuses[to]);
    edges.forEach(([a,b],index)=>{const pa=points[a],pb=points[b],wa=(focusA.has(a)||focusA.has(b))?1:0,wb=(focusB.has(a)||focusB.has(b))?1:0,weight=lerp(wa,wb,mix);ctx.strokeStyle=`rgba(230,238,233,${.12+weight*.28})`;ctx.lineWidth=.55+weight*.45;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();if(weight>.35){const flow=(storyProgress*4.1+index*.13)%1,x=lerp(pa.x,pb.x,flow),y=lerp(pa.y,pb.y,flow),g=ctx.createRadialGradient(x,y,0,x,y,14);g.addColorStop(0,`rgba(246,194,111,${.35+weight*.45})`);g.addColorStop(1,'rgba(246,194,111,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.fill()}});
    points.forEach((p,i)=>{const weight=lerp(focusA.has(i)?1:0,focusB.has(i)?1:0,mix);if(weight>.2){const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,22);g.addColorStop(0,`rgba(242,188,98,${weight*.32})`);g.addColorStop(1,'rgba(242,188,98,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.fill()}ctx.fillStyle=weight>.35?'rgba(246,198,119,.96)':'rgba(225,235,229,.58)';ctx.beginPath();ctx.arc(p.x,p.y,1.4+weight*1.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`rgba(236,242,238,${.16+weight*.38})`;ctx.lineWidth=.7;ctx.beginPath();ctx.arc(p.x,p.y,5+weight*4,0,Math.PI*2);ctx.stroke()});
    const scanX=storyProgress*width;scanLine.style.setProperty('--scan-x',`${scanX}px`);scene.style.setProperty('--image-x',`${pointerX*-5+storyProgress*-8}px`);scene.style.setProperty('--image-y',`${pointerY*-3}px`);scene.style.setProperty('--image-scale',`${1.03+storyProgress*.045}`);updateCopy(scaled);progressFill.style.transform=`scaleX(${storyProgress})`;}
  function render(){raf=0;draw()}function scheduleRender(){if(!raf)raf=requestAnimationFrame(render)}function onScroll(){storyProgress=reducedMotion?Math.round(currentScrollProgress()*4)/4:currentScrollProgress();scheduleRender()}function scrollToState(index){scrollTo({top:story.offsetTop+(story.offsetHeight-innerHeight)*clamp(index/4),behavior:reducedMotion?'auto':'smooth'})}
  tabs.forEach(b=>b.addEventListener('click',()=>scrollToState(Number(b.dataset.state))));topButtons.forEach(b=>b.addEventListener('click',()=>scrollToState(Number(b.dataset.state))));nextButton.addEventListener('click',()=>scrollToState(Math.min(4,activeState+1)));scene.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect();pointerX=((e.clientX-r.left)/r.width-.5)*2;pointerY=((e.clientY-r.top)/r.height-.5)*2;scheduleRender()});scene.addEventListener('pointerleave',()=>{pointerX=0;pointerY=0;scheduleRender()});addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',resize);resize();onScroll();
})();